# Generated by Django 6.0.6 on 2026-06-30 06:41

import cloudinary_storage.validators
import posts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=posts.storage.ImageStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, storage=posts.storage.VideoStorage(), upload_to='', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
