# Generated by Django 6.0.6 on 2026-06-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_image_alter_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trending_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
