# Generated by Django 6.0.6 on 2026-06-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_trending_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='trending_score',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
