# Generated by Django 6.0.6 on 2026-07-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_trending_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
