# Generated by Django 6.0.6 on 2026-06-25 05:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_pic',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
